[package]
authors = ["The Rust Project Developers"]
name = "rustdoc"
version = "0.0.0"

[[bin]]
name = "rustdoc"
path = "src/lib.rs"

[dependencies]
maud = "0.8.0"
maud_macros = "*"
maud-pulldown-cmark = "^0.1"
pulldown-cmark = "0.0.5"
